"""added state to template

Revision ID: 1537c363a63f
Revises: f233ebfee1fb
Create Date: 2019-04-29 19:29:54.571617

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1537c363a63f'
down_revision = 'f233ebfee1fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transformation_templates', sa.Column('pipeline_state_type_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    conn = op.get_bind()
    conn.execute("""
                 COMMENT ON COLUMN transformation_templates.pipeline_state_type_id IS 'The pipeline state that this transform is allowed to operate within.';
                
    """)
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transformation_templates', 'pipeline_state_type_id')
    # ### end Alembic commands ###
