FROM python:3

RUN mkdir /app
WORKDIR /app

COPY requirements.txt /app
RUN pip install --trusted-host pypi.python.org -r requirements.txt
COPY . /app

# ENTRYPOINT ["python", "app.py"]
CMD tail -f /dev/null
