"""empty message

Revision ID: 11eb4ef8041a
Revises: c35c252fb0bc
Create Date: 2019-02-01 16:37:48.054301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11eb4ef8041a'
down_revision = 'c35c252fb0bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
