## constants
ENVIRONMENT: dev
DOCKER_REPO: ichain/core
DEV_BUCKET: ichain-dev
PROD_BUCKET: ichain-production
UAT_BUCKET: ichain-uat
DEV_AWS_ACCOUNT: "265991248033"
PROD_AWS_ACCOUNT: "687531504312"
AWS_REGION: us-east-1
AWS_BATCH_TEST_JOB_QUEUE: core
LOGGING_CONFIG: logging.yaml
DEV_CONFIGURATION_APPLICATION_CONN_STRING: "postgresql://configurator:configurator@configurationpg/configuration_application"
CORE_VERSION: "0.0.11"

## DYNAMICS
# AWS_ACCOUNT default is set to PROD_AWS_ACCOUNT for prod and uat, DEV_AWS_ACCOUNT otherwise
# BATCH_JOB_QUEUE default is set to '<ENVIRONMENT>-core'
# ENV_BUCKET default is set to 'ichain-<ENVIRONMENT>' 
