##TODO: env should ideally set these
ENVIRONMENT: dev
ENV_BUCKET: ichain-dev

## constants
DOCKER_REPO: ichain/core
DEV_BUCKET: ichain-dev
PROD_BUCKET: ichain-production
UAT_BUCKET: ichain-uat
DEV_AWS_ACCOUNT: "265991248033"
PROD_AWS_ACCOUNT: "687531504312"
AWS_ACCOUNT: "265991248033"
AWS_REGION: us-east-1
AWS_BATCH_TEST_JOB_QUEUE: core
LOGGING_CONFIG: logging.yaml