AWS_BATCH_TEST_JOB_QUEUE: core
AWS_REGION: us-east-1
CORE_VERSION: 0.0.11
DEV_AWS_ACCOUNT: '265991248033'
DEV_BUCKET: ichain-dev
DEV_CONFIGURATION_APPLICATION_CONN_STRING: postgresql://configurator:configurator@core_configurationpg_1/configuration_application
DOCKER_REPO: ichain/core
ENVIRONMENT: dev
FORCE_POSTGRES: true
LOGGING_CONFIG: logging.yaml
PROD_AWS_ACCOUNT: '687531504312'
PROD_BUCKET: ichain-production
UAT_BUCKET: ichain-uat
