---
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: core_debug.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

#    error_file_handler:
#        class: logging.handlers.RotatingFileHandler
#        level: ERROR
#        formatter: simple
#        filename: core_errors.log
#        maxBytes: 10485760 # 10MB
#        backupCount: 20
#        encoding: utf8

loggers:
    # core:
    #     level: INFO
    #     handlers: [console]
    #     propagate: no
    botocore:
        level: DEBUG
        handlers: [debug_file_handler]
        propagate: no
    docker:
        level: DEBUG
        handlers: [debug_file_handler]
        propagate: no
root:
    level: WARN
    handlers: [debug_file_handler]
...
