BEGIN;

INSERT INTO transformation_templates (name, variable_structures, pipeline_state_type_id, last_actor)
    VALUES
        ('patient_status_enrich_cancel_before_active',
        '{"input_transform":{"datatype": "string","description": "Transform to source data from"},"active_substatus_code":{"datatype": "string","description": "Active Shipment Substatus code, e.g. SHIPMENT (customer-specific)"},"cancel_discontinue_status_code":{"datatype": "string","description": "List of Cancelled and Discontinued status codes (customer-specific)"},"bvpa_cancel_discontinue_substatus":{"datatype": "string","description": "List of accepted substatus codes used for BVPA hierarchy, e.g. [INSURANCE DENIED,COVERAGE DENIED] (customer-specific)"},"active_diff_threshold":{"datatype": "string","description": "Threshold value for Active/Cancel date difference logic (customer-specific)"},"prior_diff_threshold":{"datatype": "string","description": "Threshold value for Cancel/Prior date difference logic (customer-specific)"},"active_hierarchy":{"datatype": "string","description": "Hierarchy to assign to statuses after the first fill, e.g. ACTIVE - SHIPMENT (customer-specific)"},"remove_from_ttff":{"datatype": "string","description": "Hierarchy to assign to statuses that are ignored from TTFF (customer-specific)"},"no_status_clarity":{"datatype": "string","description": "Hierarchy to assign to cancelled/discontinued statuses with no status clarity (customer-specific)"},"bvpa_hierarchy":{"datatype": "string","description": "Hierarchy to assign to cancelled/discontinued statuses that have BVPA substatus (customer-specific)"},"hierarchy":{"datatype": "string","description": "Column name to use for Hierarchy"}}',
        (SELECT id FROM pipeline_state_types WHERE name = 'enrich'),
        'rns@integrichain.com');

COMMIT;