"""empty message

Revision ID: c7bab5c2af81
Revises: c35c252fb0bc
Create Date: 2019-02-13 20:54:04.876973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7bab5c2af81'
down_revision = 'c35c252fb0bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('extract_configurations', 'secret_type_of',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='represents the source type, eg. FTP, databse, S3 etc.',
               existing_nullable=False)
    op.add_column('pipelines', sa.Column('description', sa.String(), nullable=True))
    op.add_column('pipelines', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipelines', 'is_active')
    op.drop_column('pipelines', 'description')
    op.alter_column('extract_configurations', 'secret_type_of',
               existing_type=sa.VARCHAR(),
               comment='represents the source type, eg. FTP, databse, S3 etc.',
               existing_nullable=False)
    # ### end Alembic commands ###
