#!/bin/sh

docker build -t ichain/core:ci -f ./dockerfiles/core.dockerfile .;
docker run --rm \
  -e AWS_BATCH_TEST_JOB_QUEUE="prod_core" \
  -e AWS_ACCOUNT="687531504312" \
  -e BRANCH_NAME \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -w /usr/src/app \
  ichain/core:ci \
  bash -c "coverage run --source core /usr/local/bin/pytest tests/integration && coverage run -a --source core /usr/local/bin/pytest tests/unit && coverage report && coveralls"