#!/bin/sh

docker build -t ichain/core:citest -f ./dockerfiles/core.dockerfile .;
docker run --rm -it \
  -e ICHAIN_AWS_BATCH_TEST_JOB_QUEUE="prod_core" \
  -e ICHAIN_AWS_ACCOUNT="687531504312" \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -w /usr/src/app \
  ichain/core:citest \
  bash -c "coverage run --source core /usr/local/bin/pytest tests/integration && coverage run -a --source core /usr/local/bin/pytest tests/unit && coverage report && coveralls"