#!/bin/sh

. script/script_setup
echo $DIR

# Run the python test suite

docker build -f $DIR/dockerfiles/core.dockerfile . -t ichain/core

# Mount the entire repo and run both integration and unit tests
docker run --rm -it \
  -e AWS_DEFAULT_REGION=us-east-1 \
  -e AWS_ACCESS_KEY_ID=$(aws --profile default configure get aws_access_key_id) \
  -e AWS_SECRET_ACCESS_KEY=$(aws --profile default configure get aws_secret_access_key) \
  -v $DIR:/usr/src/app \
  -v /var/run/docker.sock:/var/run/docker.sock \
  ichain/core \
  bash -c "coverage run --source core /usr/local/bin/pytest tests/unit tests/integration && coverage report && coveralls"
