#!/bin/sh

. script/script_setup
echo $DIR

# Build the python 3.7 image so the requirements are up to date
docker build -f $DIR/dockerfiles/python3-7.dockerfile . -t ichain/python:3.7

# Kind of a big commmand that:
#  mounts the repo to /usr/src/app
#  mounts your home directory to /host/home
#  sets up AWS credentials
docker run --rm -it \
  -v $DIR:/usr/src/app \
  -v $HOME:/host/home \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -e AWS_DEFAULT_REGION=us-east-1 \
  -v $HOME:/root \
  -e AWS_ACCESS_KEY_ID=banana \
  -e AWS_SECRET_ACCESS_KEY=hot_dog \
  ichain/python:3.7 \
  /bin/bash
