#!/bin/sh

. script/script_setup
echo $DIR
TYPE=$1
docker-compose stop;
docker-compose rm -f configurationpg;
if [ "$1" == "--build" ]; then
    docker-compose build;
    TYPE=$2
fi
AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
docker-compose up -d;
if [ "$TYPE" == "--gui" ]; then
    open -a Terminal ./script/gui_api
fi

docker-compose exec notebook /bin/bash -c "cd core/core/database && \
alembic upgrade head"



## adding the ssh daemon here so we don't run it in prod by accident
docker-compose exec notebook /bin/bash -c "apt-get update && \
apt-get install -y openssh-server && \
mkdir /var/run/sshd && \
useradd -ms /bin/bash corebot_remote && \
 echo -e 'corebot_remote\ncorebot_remote' | passwd corebot_remote && \
ssh-keygen -R notebook && \
service ssh start && \
cp -r /host/home/.aws /home/corebot_remote/.aws && \
chown corebot_remote /home/corebot_remote/.aws/* && \
chmod -R 644 /home/corebot_remote/.aws"  
script/dev_shell $TYPE

