#!/bin/sh

docker-compose stop;
docker-compose build;
AWS_ACCESS_KEY_ID=$(aws --profile default configure get aws_access_key_id) \
  AWS_SECRET_ACCESS_KEY=$(aws --profile default configure get aws_secret_access_key) \
  docker-compose up -d;

docker-compose run --rm console