#!/bin/sh

. script/script_setup
echo $DIR
TYPE=$1
docker-compose stop;
docker-compose rm -f configurationpg;

AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
docker-compose up -d notebook configurationpg;

docker-compose exec notebook /bin/bash -c "cd core/core/database && \
alembic upgrade head"
