#!/bin/sh

. script/script_setup
echo $DIR

# Build the core image so the requirements are up to date
docker-compose build console;

# Mount the entire repo and run only the unit tests
AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
docker-compose run \
  --rm \
  console \
  bash -c "coverage run --source core /usr/local/bin/pytest tests/integration tests/unit && coverage report";