#!/bin/sh

export PGPASSWORD=configurator

psql -w -h localhost -U configurator -d configuration_application -f seeds/2019.02.13__14.02.sql
psql -w -h localhost -U configurator -d configuration_application -f seeds/2019.04.15__14.19.sql
psql -w -h localhost -U configurator -d configuration_application -f seeds/2019.07.08__09.41.sql
psql -w -h localhost -U configurator -d configuration_application -f seeds/2019.07.19__09.20.sql
psql -w -h localhost -U configurator -d configuration_application -f seeds/2019.08.05__13.40.sql
psql -w -h localhost -U configurator -d configuration_application -f seeds/patient_status_date_standardization_template.sql
psql -w -h localhost -U configurator -d configuration_application -f seeds/patient_status_date_standardization.sql
