#!/bin/sh

export PGPASSWORD=configurator

psql -w -h localhost -U configurator -d configuration_application -f seeds/2019.02.13__14.02.sql
psql -w -h localhost -U configurator -d configuration_application -f seeds/2019.04.15__14.19.sql
psql -w -h localhost -U configurator -d configuration_application -f seeds/2019.07.08__09.41.sql
psql -w -h localhost -U configurator -d configuration_application -f seeds/2019.07.19__09.20.sql
psql -w -h localhost -U configurator -d configuration_application -f seeds/2019.08.05__13.40.sql
psql -w -h localhost -U configurator -d configuration_application -f seeds/patient_status_standardize_dates_template.sql
psql -w -h localhost -U configurator -d configuration_application -f seeds/patient_status_standardize_dates.sql
psql -w -h localhost -U configurator -d configuration_application -f seeds/patient_status_standardize_numbers_template.sql 
psql -w -h localhost -U configurator -d configuration_application -f seeds/patient_status_standardize_numbers.sql
psql -w -h localhost -U configurator -d configuration_application -f seeds/patient_status_fill_rate_template.sql
psql -w -h localhost -U configurator -d configuration_application -f seeds/patient_status_fill_rate.sql
psql -w -h localhost -U configurator -d configuration_application -f seeds/enrich_pending_too_long_template.sql
psql -w -h localhost -U configurator -d configuration_application -f seeds/enrich_pending_too_long.sql
psql -w -h localhost -U configurator -d configuration_application -f seeds/patient_status_master_patient_status_template.sql
psql -w -h localhost -U configurator -d configuration_application -f seeds/patient_status_master_patient_status.sql
psql -w -h localhost -U configurator -d configuration_application -f seeds/patient_status_master_patient_status_variables.sql
psql -w -h localhost -U configurator -d configuration_application -f seeds/patient_status_master_patient_substatus_template.sql
psql -w -h localhost -U configurator -d configuration_application -f seeds/patient_status_master_patient_substatus.sql
psql -w -h localhost -U configurator -d configuration_application -f seeds/patient_status_master_patient_substatus_variables.sql
psql -w -h localhost -U configurator -d configuration_application -f seeds/patient_status_enrich_patient_journey_hierarchy_template.sql
psql -w -h localhost -U configurator -d configuration_application -f seeds/patient_status_enrich_patient_journey_hierarchy.sql
psql -w -h localhost -U configurator -d configuration_application -f seeds/patient_status_enrich_patient_journey_hierarchy_variables.sql
psql -w -h localhost -U configurator -d configuration_application -f seeds/patient_status_enrich_fill_null_long_pat_id.sql
psql -w -h localhost -U configurator -d configuration_application -f seeds/patient_status_ingest_brand_derivation.sql
psql -w -h localhost -U configurator -d configuration_application -f seeds/patient_status_enrich_fill_null_ref_date.sql