#!/bin/sh
docker-compose exec airflow /bin/bash -c "cd /root/airflow/dags/ && touch pause_executor"
sleep 3 # gives our airflow executor time to stop querying configurations
docker-compose exec notebook /bin/bash -c "cd /usr/src/app/script && python seed_loader.py"
docker-compose exec airflow /bin/bash -c "cd /root/airflow/dags/ && rm -f pause_executor"