#!/bin/sh

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

if ! [[ $(which docker) && $(docker --version) ]]; then
   echo "Please install docker before running this script."
   exit
fi

AWS_ACCESS_KEY_ID=$(aws --profile dev configure get aws_access_key_id)
AWS_SECRET_ACCESS_KEY=$(aws --profile dev configure get aws_secret_access_key)