#!/bin/sh

. script/script_setup
echo $DIR

# Run the python test suite

# Build the core image so the requirements are up to date
docker-compose build console;

# Mount the entire repo and run only the unit tests
docker-compose run --rm console \
  bash -c "coverage run --source core /usr/local/bin/pytest tests/unit && coverage report $1"
