#!/bin/sh

LOG=
LINE=

while [ -n "$1" ]; do 
 
    case "$1" in
 
    --h) echo '
          _       __________________  _________ _______  _______ _________ _______  _ 
|\     /|( (    /|\__   __/\__   __/  \__   __/(  ____ \(  ____ \\\__   __/( ___ _ \( )
| )   ( ||  \  ( |   ) (      ) (        ) (   | (    \/| (    \/   ) (   | (    \/| |
| |   | ||   \ | |   | |      | |        | |   | (__    | (_____    | |   | (_____ | |
| |   | || (\ \) |   | |      | |        | |   |  __)   (_____  )   | |   (_____  )| |
| |   | || | \   |   | |      | |        | |   | (            ) |   | |         ) |(_)
| (___) || )  \  |___) (___   | |        | |   | (____/\/\____) |   | |   /\____) | _ 
(_______)|/    )_)\_______/   )_(        )_(   (_______/\_______)   )_(   \_______)(_)
                                    
test yo stuff! options:\n-log\tprints stdout during py.test runs (this includes debug logs).\n-line\tadds the coverage missed lines to the coverage report.\n' 
        exit 0 ;;
 
    --log) LOG="-s" ;;
 
    --line) LINE="-m" ;;
 
    *) echo "Option $1 not recognized. try '-h' for help." 
       exit 0 ;; 
 
    esac
 
    shift
 
done
pip3 install -r requirements/api.txt
coverage run --source core /usr/local/bin/pytest $LOG tests/unit && coverage report $LINE
