FROM python:3

SHELL ["/bin/bash", "-c"]

ENV PYTHONPATH=/usr/local/lib/python3.6/site-packages:/app

RUN mkdir /app
WORKDIR /app/phi_nightcrawler

COPY requirements.txt /phi_nightcrawler
COPY . /app/phi_nightcrawler

RUN pip install --trusted-host pypi.python.org -r requirements.txt

CMD tail -f /dev/null
