FROM python:3

RUN mkdir /app/phi_nightcrawler
WORKDIR /app/phi_nightcrawler

COPY requirements.txt /phi_nightcrawler
COPY . /app/phi_nightcrawler

RUN pip install --trusted-host pypi.python.org -r requirements.txt

CMD tail -f /dev/null
