FROM python:3

RUN mkdir /phi_nightcrawler
WORKDIR /phi_nightcrawler

COPY requirements.txt /phi_nightcrawler
RUN pip install --trusted-host pypi.python.org -r requirements.txt
COPY . /phi_nightcrawler

CMD tail -f /dev/null
